"""add_theme_column_to_user_settings

Revision ID: 0b9aeccb5049
Revises: aa740a38d604
Create Date: 2025-11-06 15:14:51.277129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b9aeccb5049'
down_revision: Union[str, None] = 'aa740a38d604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('theme', sa.String(length=20), server_default='light', nullable=False, comment='Tema interfaccia utente (light, dark)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'theme')
    # ### end Alembic commands ###

