"""expand_task_description_for_richtext

Revision ID: 1c9d4e5f6a7b
Revises: 0b9aeccb5049
Create Date: 2025-11-11 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9d4e5f6a7b'
down_revision: Union[str, None] = '0b9aeccb5049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Modifica la colonna description da VARCHAR(255) a TEXT per supportare contenuto rich-text
    op.alter_column('tasks', 'description',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.Text(),
                    existing_nullable=True,
                    existing_comment='Descrizione dettagliata task')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Ripristina la colonna description a VARCHAR(255)
    op.alter_column('tasks', 'description',
                    existing_type=sa.Text(),
                    type_=sa.VARCHAR(length=255),
                    existing_nullable=True,
                    existing_comment='Descrizione dettagliata task')
    # ### end Alembic commands ###

