"""add_accent_color_to_user_settings

Revision ID: 2c1a7ec5ca1b
Revises: 0b9aeccb5049
Create Date: 2025-11-11 15:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c1a7ec5ca1b"
down_revision: Union[str, None] = "1c9d4e5f6a7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ACCENT_COLOR_DEFAULT = "#7A5BFF"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_settings",
        sa.Column(
            "accent_color",
            sa.String(length=20),
            nullable=False,
            server_default=ACCENT_COLOR_DEFAULT,
            comment="Colore accento interfaccia (HEX)",
        ),
    )
    op.execute(
        f"UPDATE user_settings SET accent_color = '{ACCENT_COLOR_DEFAULT}' WHERE accent_color IS NULL;"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "accent_color")
    # ### end Alembic commands ###


