"""add_user_settings_table

Revision ID: aa740a38d604
Revises: 001
Create Date: 2025-11-06 15:08:38.600814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa740a38d604'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificatore univoco impostazioni'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment="Riferimento all'utente"),
    sa.Column('language', sa.String(length=5), server_default='it', nullable=False, comment='Codice lingua ISO (it, en, es, fr, etc.)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Data creazione'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Data ultimo aggiornamento'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    
    # Crea trigger per updated_at (riusa la funzione esistente)
    op.execute("""
    CREATE TRIGGER update_user_settings_updated_at
        BEFORE UPDATE ON user_settings
        FOR EACH ROW
        EXECUTE FUNCTION update_updated_at_column();
    """)
    
    # Concedi permessi al ruolo authenticated
    op.execute("GRANT ALL PRIVILEGES ON TABLE user_settings TO authenticated;")
    
    op.alter_column('tasks', 'color',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_comment='Colore per categorizzazione visiva (green, purple, orange, cyan, pink, yellow)',
               existing_server_default=sa.text("'green'::character varying"))
    op.alter_column('tasks', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='Flag completamento task',
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='Timestamp creazione',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='Timestamp ultimo aggiornamento',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_tasks_completed'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_date_time'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_tenant_date'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_tenant_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_completed'), 'tasks', ['completed'], unique=False)
    op.create_index(op.f('ix_tasks_date_time'), 'tasks', ['date_time'], unique=False)
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.drop_table_comment(
        'tasks',
        existing_comment='Attività degli utenti (RLS disabilitato in locale, abilitato in produzione)',
        schema=None
    )
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='Timestamp registrazione',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('users_name_user_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_name_user'), 'users', ['name_user'], unique=True)
    op.drop_table_comment(
        'users',
        existing_comment='Utenti registrati nel sistema (multi-tenant)',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'Utenti registrati nel sistema (multi-tenant)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_users_name_user'), table_name='users')
    op.create_unique_constraint(op.f('users_name_user_key'), 'users', ['name_user'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='Timestamp registrazione',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'tasks',
        'Attività degli utenti (RLS disabilitato in locale, abilitato in produzione)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_date_time'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_completed'), table_name='tasks')
    op.create_index(op.f('idx_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_tasks_tenant_date'), 'tasks', ['tenant_id', sa.literal_column('date_time DESC')], unique=False)
    op.create_index(op.f('idx_tasks_date_time'), 'tasks', [sa.literal_column('date_time DESC')], unique=False)
    op.create_index(op.f('idx_tasks_completed'), 'tasks', ['completed'], unique=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='Timestamp ultimo aggiornamento',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='Timestamp creazione',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tasks', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='Flag completamento task',
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'color',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='Colore per categorizzazione visiva (green, purple, orange, cyan, pink, yellow)',
               existing_server_default=sa.text("'green'::character varying"))
    
    # Rimuovi trigger prima di droppare la tabella
    op.execute("DROP TRIGGER IF EXISTS update_user_settings_updated_at ON user_settings;")
    
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###

